import type { ProspectionImportInput } from "@/lib/prospects";

/** Incrémenter à chaque nouvel import Cursor → déclenche le merge au prochain chargement */
export const IA_PROSPECT_QUEUE_VERSION = 2;

/**
 * File d'attente remplie par Cursor lors d'une recherche prospection.
 * Après import automatique, vider le tableau et incrémenter IA_PROSPECT_QUEUE_VERSION.
 *
 * Recherche : terrassiers · Annecy & alentours (score site < 50 uniquement)
 */
export const iaProspectQueue: ProspectionImportInput[] = [
  {
    company: "Entreprise Brun et Fils",
    city: "Meythet",
    trade: "terrassier",
    phone: "04 50 57 50 68",
    address: "28 avenue du Pont de Tasset, 74960 Meythet",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Présence Google Maps seule", "Pas de formulaire devis"],
    severity: "critique",
    severityNote: "Aucune vitrine en ligne — invisible pour les particuliers qui cherchent un terrassier sur Annecy/Meythet.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.1,
    googleReviewCount: 8,
  },
  {
    company: "Chappaz Julien TP",
    city: "Charvonnex",
    trade: "terrassier",
    phone: "04 50 60 30 46",
    address: "1219 route d'Annecy, 74370 Charvonnex",
    websiteScore: 15,
    websiteIssues: ["Aucun site web", "Fiche annuaire uniquement", "Pas de portfolio chantiers"],
    severity: "critique",
    severityNote: "TP local depuis 1969 sans site — gros retard digital sur le bassin annécien.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.6,
    googleReviewCount: 14,
  },
  {
    company: "PEGAT SARL Terrassement",
    city: "Cran-Gevrier",
    trade: "terrassier",
    phone: "04 50 67 46 14",
    address: "ZI Les Îles, rue de la Digue, 74960 Cran-Gevrier",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Pas de visibilité SEO locale"],
    severity: "critique",
    severityNote: "Terrassier en zone industrielle Cran-Gevrier sans vitrine — opportunité site devis + réalisations.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Stéphane Chatel TP",
    city: "Pringy",
    trade: "terrassier",
    phone: "04 50 27 26 81",
    address: "217 rue des Nouvelles Contamines, 74370 Pringy",
    websiteScore: 16,
    websiteIssues: ["Aucun site web", "Contact téléphone uniquement"],
    severity: "critique",
    severityNote: "Artisan TP Pringy sans présence web — les concurrents Edelweiss/Enrobalp captent la demande en ligne.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "SCDF Laureti Claude & Benedetti",
    city: "Annecy-le-Vieux",
    trade: "terrassier",
    phone: "06 11 86 90 26",
    address: "17 chemin des Carrières, 74940 Annecy-le-Vieux",
    websiteScore: 10,
    websiteIssues: ["Aucun site web", "Nom peu lisible en ligne (BLTP)"],
    severity: "critique",
    severityNote: "Entreprise TP Annecy-le-Vieux absente du web — refonte identité + site prioritaire.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Roudil TP",
    city: "Annecy",
    trade: "terrassier",
    phone: "04 50 57 05 68",
    address: "27B avenue de Novel, 74000 Annecy",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Pas de page Google Business optimisée"],
    severity: "critique",
    severityNote: "TP en centre Annecy sans site — perte de leads particuliers villa/piscine.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "ABM TRANS'ALP",
    city: "Seynod",
    trade: "terrassier",
    phone: "04 50 65 03 81",
    address: "10 rue des Frères Montgolfier, 74600 Seynod",
    websiteScore: 11,
    websiteIssues: ["Aucun site web", "Transport/TP sans vitrine"],
    severity: "critique",
    severityNote: "Société TP Seynod invisible en ligne — site vitrine + zone d'intervention à créer.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Michel Tardivel TP",
    city: "Annecy",
    trade: "terrassier",
    phone: "04 50 51 42 80",
    address: "18 avenue de Cran, 74000 Annecy",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Référencé annuaires uniquement"],
    severity: "critique",
    severityNote: "Terrassier Annecy centre sans site — concurrence Levet/Mithieux domine la recherche Google.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 3.9,
    googleReviewCount: 6,
  },
  {
    company: "Ismaïl Ozer TP",
    city: "Annecy",
    trade: "terrassier",
    address: "20 avenue de Mandallaz, 74000 Annecy",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Pas de présence digitale"],
    severity: "critique",
    severityNote: "TP Annecy sans aucune vitrine — création site urgente pour crédibilité chantier.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Jacquet VRD Terrassement",
    city: "Argonay",
    trade: "terrassier",
    phone: "06 11 11 07 23",
    address: "91 chemin des Vernes, 74370 Argonay",
    website: "https://vrd-terrassement-argonay.fr",
    websiteScore: 22,
    websiteIssues: ["Site injoignable (erreur 500)", "Domaine existant mais non fonctionnel", "Pas de devis en ligne"],
    severity: "critique",
    severityNote: "Domaine acheté mais site down — image très négative, refonte ou remise en ligne immédiate.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.3,
    googleReviewCount: 11,
  },
  {
    company: "Rachid Travaux Publics Enrobés",
    city: "Meythet",
    trade: "terrassier",
    address: "41 route de Cotfa, 74960 Meythet",
    websiteScore: 10,
    websiteIssues: ["Aucun site web", "Enrobés/TP sans présence en ligne"],
    severity: "critique",
    severityNote: "TP Meythet totalement absent du web — site simple vitrine + téléphone recommandé.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Alain Razzar TP",
    city: "Poisy",
    trade: "terrassier",
    phone: "04 50 46 44 64",
    address: "60 chemin de la Courbassière, 74330 Poisy",
    websiteScore: 15,
    websiteIssues: ["Aucun site web", "Artisan local non référencé"],
    severity: "critique",
    severityNote: "Terrassier Poisy sans site — zone Epagny/Poisy très concurrentielle, vitrine manquante.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Robert Travaux Publics",
    city: "Poisy",
    trade: "terrassier",
    phone: "04 50 77 43 21",
    address: "326 route d'Allonzier, 74330 Choisy",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Location mini-pelle sans page dédiée"],
    severity: "critique",
    severityNote: "RTP secteur Poisy/Choisy sans vitrine — perte de demandes piscine/terrassement.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.4,
    googleReviewCount: 9,
  },
  {
    company: "MC Paysage VRD",
    city: "Poisy",
    trade: "terrassier",
    address: "271 route des Maraîchères, 74330 Poisy",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "VRD/terrassement non visible en ligne"],
    severity: "critique",
    severityNote: "Activité VRD/terrassement Poisy sans site — combo paysage+TP invisible sur Google.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Clerc-Renaud TP",
    city: "Sales",
    trade: "terrassier",
    phone: "04 50 69 35 12",
    address: "405 route d'Hauteville, 74150 Sales",
    websiteScore: 16,
    websiteIssues: ["Aucun site web", "Albanais — concurrence Orsapa/SATP"],
    severity: "critique",
    severityNote: "TP Albanais (Sales) sans présence web — secteur Rumilly/Annecy très disputé en ligne.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "MFTP Mamain Frères",
    city: "Marcellaz-Albanais",
    trade: "terrassier",
    phone: "06 38 43 75 27",
    address: "421 rue des Écoles, 74150 Marcellaz-Albanais",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Entreprise familiale invisible"],
    severity: "critique",
    severityNote: "Maçonnerie/TP Marcellaz sans site — image artisanale faible malgré proximité Annecy.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Gagnière Thierry TP",
    city: "Marcellaz-Albanais",
    trade: "terrassier",
    phone: "04 50 69 75 94",
    address: "698 chemin du Creux, 74150 Marcellaz-Albanais",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Pas de photos chantiers en ligne"],
    severity: "critique",
    severityNote: "Terrassier Albanais sans vitrine — site one-page avec galerie chantiers recommandé.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Ribeiro Père et Fils TP",
    city: "Marcellaz-Albanais",
    trade: "terrassier",
    phone: "06 71 17 98 82",
    address: "1607 route de Contentenaz, 74150 Marcellaz-Albanais",
    websiteScore: 11,
    websiteIssues: ["Aucun site web", "Mobile uniquement pour contact"],
    severity: "critique",
    severityNote: "TP familial Albanais 100 % offline — opportunité site mobile-first + click-to-call.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Martenex TP",
    city: "Rumilly",
    trade: "terrassier",
    address: "122 route d'Aix-les-Bains, 74150 Rumilly",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Rumilly — zone TP dense"],
    severity: "critique",
    severityNote: "TP Rumilly sans site alors que SATP/Odyssée/Grosjean dominent — vitrine indispensable.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "SG Schillaci TP",
    city: "Mognard",
    trade: "terrassier",
    phone: "04 79 54 08 03",
    address: "ZAC du Sauvage, 73410 Mognard",
    websiteScore: 15,
    websiteIssues: ["Aucun site web", "Entreprise Savoie/Albanais absente du web"],
    severity: "critique",
    severityNote: "TP entre Rumilly et Entrelacs sans vitrine — refonte image pro via site AKNO.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Picon Régis TP",
    city: "Entrelacs",
    trade: "terrassier",
    phone: "06 09 85 73 43",
    address: "Chemin Sur la Roche, 73410 Entrelacs",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Confusion avec Ets Picon carrière"],
    severity: "critique",
    severityNote: "TP Entrelacs sans site distinct — identité floue en ligne, site dédié terrassement à créer.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Groupe Seret TP",
    city: "La Biolle",
    trade: "terrassier",
    phone: "04 79 54 79 00",
    address: "1770 route d'Annecy, 73410 La Biolle",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Groupe TP Albanais non référencé"],
    severity: "critique",
    severityNote: "Groupe TP secteur Rumilly/Annecy sans présence web — gros potentiel site corporate léger.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "SARL HBTP et Paysage",
    city: "Montcel",
    trade: "terrassier",
    phone: "06 24 71 43 14",
    address: "1630 route de Lachat, 73100 Montcel",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "TP + paysage invisible"],
    severity: "critique",
    severityNote: "TP/paysage entre Aix et Albanais sans vitrine — double activité à valoriser sur un site.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Rick TP",
    city: "Entrelacs",
    trade: "terrassier",
    phone: "07 57 43 48 57",
    address: "651 route d'Orly, 73410 Entrelacs",
    websiteScore: 11,
    websiteIssues: ["Aucun site web", "Contact mobile uniquement"],
    severity: "critique",
    severityNote: "Petit TP Entrelacs totalement invisible — site vitrine rapide à fort ROI.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Janin BTP",
    city: "Entrelacs",
    trade: "terrassier",
    phone: "06 17 28 41 55",
    address: "200 rue du Semnoz, 73410 Entrelacs",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "BTP généraliste sans page TP"],
    severity: "critique",
    severityNote: "BTP Entrelacs sans site — terrassement/VRD à mettre en avant sur vitrine locale.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Bogey TP",
    city: "Grésy-sur-Aix",
    trade: "terrassier",
    phone: "06 47 82 32 16",
    address: "549 chemin des Bogeys, 73100 Grésy-sur-Aix",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Intervient secteur Annecy/Aix"],
    severity: "critique",
    severityNote: "TP Grésy/Aix sans vitrine — couvre bassin annécien mais introuvable sur Google.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Ferrand TP",
    city: "Chainaz-les-Frasses",
    trade: "terrassier",
    phone: "04 50 52 34 97",
    address: "Les Frasses Bas, 74540 Chainaz-les-Frasses",
    websiteScore: 15,
    websiteIssues: ["Aucun site web", "Secteur Fillière/Sillingy"],
    severity: "critique",
    severityNote: "TP Fillière sans site — zone en expansion résidentielle, vitrine manquante.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "RCPS Terrassement",
    city: "Annecy",
    trade: "terrassier",
    phone: "06 01 20 45 67",
    websiteScore: 10,
    websiteIssues: ["Aucun site web", "Nom générique difficile à trouver"],
    severity: "critique",
    severityNote: "Terrassier Annecy/Rumilly sans aucune présence — site + SEO local prioritaire.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "CC TP 74 VRD Terrassement",
    city: "Annecy",
    trade: "terrassier",
    address: "1 rue du Lac, 74000 Annecy",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Sigle peu explicite en ligne"],
    severity: "critique",
    severityNote: "TP Annecy centre (CC TP 74) absent du web — identité et site à structurer.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Frédéric Munier TP",
    city: "Cran-Gevrier",
    trade: "terrassier",
    address: "3 avenue Auguste Renoir, 74960 Cran-Gevrier",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Cran-Gevrier — forte demande résidentielle"],
    severity: "critique",
    severityNote: "Terrassier Cran-Gevrier sans vitrine — quartier dense en construction neuve.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Gonzalez TP",
    city: "Meythet",
    trade: "terrassier",
    address: "10 rue de l'Euro, 74960 Meythet",
    websiteScore: 11,
    websiteIssues: ["Aucun site web", "ZI Meythet invisible en ligne"],
    severity: "critique",
    severityNote: "TP ZI Meythet sans site — proximité aéroport/zone commerciale, vitrine pro manquante.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "3Z Rénov Terrassement",
    city: "Metz-Tessy",
    trade: "terrassier",
    address: "25 impasse du Champ Lacour, 74370 Metz-Tessy",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Rénov + TP non différenciés en ligne"],
    severity: "critique",
    severityNote: "Rénov/terrassement Epagny-Metz-Tessy sans site — double métier à clarifier sur vitrine.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Maloux TP",
    city: "Allonzier-la-Caille",
    trade: "terrassier",
    address: "151 route du Cimetière, 74350 Allonzier-la-Caille",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Secteur Epagny nord"],
    severity: "critique",
    severityNote: "TP Allonzier sans vitrine — couvre Epagny/Annecy nord, invisible pour les particuliers.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Guillermin Pascal TP",
    city: "Vaulx",
    trade: "terrassier",
    address: "1569 route de Nonglard, 74150 Vaulx",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Albanais sud"],
    severity: "critique",
    severityNote: "Artisan TP Vaulx (Albanais) sans site — concurrence Rumilly très présente en ligne.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "David TP et Fils",
    city: "La Tour",
    trade: "terrassier",
    address: "124 lotissement Mas des Grenisses, 74250 La Tour",
    websiteScore: 11,
    websiteIssues: ["Aucun site web", "Pays de Fillière / Annecy nord"],
    severity: "critique",
    severityNote: "TP familial La Tour sans vitrine — secteur Fillière en croissance, site manquant.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Forestier TP",
    city: "Bonne",
    trade: "terrassier",
    address: "813 route de la Limargue, 74380 Bonne",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Arrière-pays annécien"],
    severity: "critique",
    severityNote: "TP Bonne/Fillière sans présence web — image locale faible malgré zone résidentielle.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Jean Arcade & Fils TP",
    city: "Bonneville",
    trade: "terrassier",
    address: "73 rue du Pont, 74130 Bonneville",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Arve / Bonneville"],
    severity: "critique",
    severityNote: "TP Bonneville sans site — lien Annecy/Arve, vitrine à créer pour crédibilité.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "VHM Canalisation VRD",
    city: "Epagny Metz-Tessy",
    trade: "terrassier",
    address: "17 impasse des Grandes Resses, 74330 Epagny Metz-Tessy",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "VRD/terrassement Epagny"],
    severity: "critique",
    severityNote: "VRD Epagny sans vitrine — zone la plus dynamique du Grand Annecy, site urgent.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Nouveau Bureau TP",
    city: "Chavanod",
    trade: "terrassier",
    address: "1 route des Creuses, 74650 Chavanod",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Chavanod/Annecy sud"],
    severity: "critique",
    severityNote: "TP Chavanod sans site — proximité Annecy-le-Vieux, demande villa/piscine forte.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Varol Maçonnerie Terrassement",
    city: "Annecy",
    trade: "terrassier",
    address: "104 route de Sacconges, 74000 Annecy",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Maçonnerie + terrassement"],
    severity: "critique",
    severityNote: "Maçon/terrassier Annecy sans site — double compétence à valoriser en ligne.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "BEUGNET SADDIER TP",
    city: "Cran-Gevrier",
    trade: "terrassier",
    address: "9 rue des Terrasses, 74960 Cran-Gevrier",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Cran-Gevrier résidentiel"],
    severity: "critique",
    severityNote: "TP Cran-Gevrier sans vitrine — rue des Terrasses, quartier à fort potentiel local.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Annecy Services TP",
    city: "Meythet",
    trade: "terrassier",
    address: "3 rue de l'Égalité, 74960 Meythet",
    websiteScore: 11,
    websiteIssues: ["Aucun site web", "Nom générique — SEO impossible"],
    severity: "critique",
    severityNote: "« Annecy Services » introuvable sur Google sans site — refonte naming + vitrine.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Société SNB TP",
    city: "Meythet",
    trade: "terrassier",
    address: "6 rue du Chauderon, 74960 Meythet",
    websiteScore: 10,
    websiteIssues: ["Aucun site web", "Sigle opaque", "Pas de devis en ligne"],
    severity: "critique",
    severityNote: "TP Meythet (SNB) totalement invisible — site one-page + Google Business à créer.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "BKH Construction Terrassement",
    city: "Rumilly",
    trade: "terrassier",
    address: "rue de la Broise, 74150 Rumilly",
    websiteScore: 12,
    websiteIssues: ["Aucun site web", "Construction + TP Rumilly"],
    severity: "critique",
    severityNote: "Constructeur/TP Rumilly sans vitrine — marché Albanais compétitif, site nécessaire.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Société des 2 Savoie TP",
    city: "Saint-Eusèbe",
    trade: "terrassier",
    address: "31 impasse des Grives, 74150 Saint-Eusèbe",
    websiteScore: 13,
    websiteIssues: ["Aucun site web", "Rumilly/Albanais"],
    severity: "critique",
    severityNote: "TP Albanais sans site — identité « 2 Savoie » à clarifier sur vitrine pro.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "Famy Pays de Savoie TP",
    city: "Alby-sur-Chéran",
    trade: "terrassier",
    address: "19 rue Moutti Sud, 74540 Alby-sur-Chéran",
    websiteScore: 14,
    websiteIssues: ["Aucun site web", "Entre Annecy et Rumilly"],
    severity: "critique",
    severityNote: "TP Alby sans vitrine — position géographique idéale, visibilité web nulle.",
    iaSearchLabel: "terrassier · Annecy & alentours",
  },
  {
    company: "SARL Deletraz TP",
    city: "Villaz",
    trade: "terrassier",
    phone: "04 50 64 91 68",
    address: "500 route des Futaies, 74370 Villaz",
    website: "https://deletraz-tp.fr",
    websiteScore: 38,
    websiteIssues: ["Design daté type template 2015", "Captcha math sur formulaire contact", "Peu mobile-friendly", "Pas de galerie chantiers récente"],
    severity: "haute",
    severityNote: "Site fonctionnel mais vieillot et peu rassurant — refonte vitrine moderne pour convertir les devis villa/piscine.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.2,
    googleReviewCount: 18,
  },
  {
    company: "Net TP 74",
    city: "La Balme-de-Sillingy",
    trade: "terrassier",
    phone: "06 75 72 69 24",
    address: "La Balme-de-Sillingy, 74330",
    website: "https://www.net-tp74.fr",
    websiteScore: 42,
    websiteIssues: ["Site one-page minimal", "Fautes orthographe (« travaillions »)", "Peu de preuves sociales", "Design générique"],
    severity: "haute",
    severityNote: "Site basique Wix-like — 20 ans d'expérience non valorisés, refonte pour crédibilité Sillingy/Annecy.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.5,
    googleReviewCount: 7,
  },
  {
    company: "VBJ Maçonnerie",
    city: "Poisy",
    trade: "terrassier",
    phone: "06 20 28 86 93",
    address: "1690 route d'Annecy, 74330 Poisy",
    website: "https://vbjmaconnerie.fr",
    websiteScore: 44,
    websiteIssues: ["Template générique", "Bandeau cookies intrusif", "Terrassement noyé dans maçonnerie", "Peu de CTA devis"],
    severity: "haute",
    severityNote: "Site maçonnerie généraliste peu orienté terrassement — UX datée, manque de focus TP/devis rapide.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.0,
    googleReviewCount: 5,
  },
  {
    company: "Burnier VRD Aménagement",
    city: "Argonay",
    trade: "terrassier",
    phone: "06 11 11 07 16",
    address: "91 route des Vernes, 74370 Argonay",
    website: "https://www.burniervrdamenagement.fr",
    websiteScore: 46,
    websiteIssues: ["Site one-page léger", "Peu de réalisations photo", "SEO local faible", "Formulaire basique"],
    severity: "haute",
    severityNote: "Site correct mais minimal — petit terrassement/accès difficiles mal valorisés, upgrade vitrine recommandé.",
    iaSearchLabel: "terrassier · Annecy & alentours",
    googleRating: 4.7,
    googleReviewCount: 22,
  },
];
